# MediaPipe subgraph that smoothes face landmarks.

type: "FaceLandmarksSmoothing"

input_stream: "NORM_LANDMARKS:landmarks"
input_stream: "IMAGE_SIZE:input_image_size"
output_stream: "NORM_FILTERED_LANDMARKS:filtered_landmarks"

# Applies smoothing to a face landmark list. The filter options were handpicked
# to achieve better visual results.
node {
  calculator: "LandmarksSmoothingCalculator"
  input_stream: "NORM_LANDMARKS:landmarks"
  input_stream: "IMAGE_SIZE:input_image_size"
  output_stream: "NORM_FILTERED_LANDMARKS:filtered_landmarks"
  node_options: {
    [type.googleapis.com/mediapipe.LandmarksSmoothingCalculatorOptions] {
       one_euro_filter {
         min_cutoff: 0.001
         beta: 60.0
       }
    }
  }
}
